default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: username
  password: password
  host: <%= ENV['IP'] %>

development:
  <<: *default
  database: prophet_data_development

test:
  <<: *default
  database: prophet_data_test

production:
  <<: *default
  database: prophet_data_production
